In [3]:
import numpy as np
import pandas as pd

In [9]:
nums = np.random.randint(0, 360, 20)

In [15]:
nums

array([142,  59, 100, 127, 289, 111, 264, 156, 194, 225, 105, 296, 263,
       341,  32, 315, 156, 191, 207, 138])

In [13]:
np.sin(nums)

array([-0.58779501,  0.63673801, -0.50636564,  0.97263007, -0.02652102,
       -0.86455145,  0.10601749, -0.88178462, -0.70238633, -0.93009488,
       -0.97053528,  0.63676125, -0.77944719,  0.99060323,  0.55142668,
        0.74513326, -0.88178462,  0.59490855, -0.33830503, -0.22805226])

In [19]:
np.sin(30)

-0.9880316240928618

In [21]:
np.sin(np.radians(30))

0.49999999999999994

---

In [24]:
X_degrees = np.random.uniform(0, 360, 5000)

In [26]:
X_degrees

array([312.64843549, 305.22892228, 133.23654368, ...,  23.16577627,
       358.11945221, 312.47094354])

In [28]:
X_radians = np.radians(X_degrees)

In [30]:
y = np.sin(X_radians)

## Creating Dataset

### Uniformly spaced dataset

In [82]:
X_degrees_uniform = np.arange(0, 360, 0.1)
X_radians_uniform = np.radians(X_degrees_uniform)
y_uniform = np.sin(X_radians_uniform)

In [84]:
print("Uniform Sample (Degrees):", X_degrees_uniform[:10])

Uniform Sample (Degrees): [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


Number of elemnts: (stop - start) / step
(360 - 0) / 0.1 = 3600

In [52]:
X_radians_uniform.size

3600

In [116]:
y_uniform[:10]

array([0.        , 0.00174533, 0.00349065, 0.00523596, 0.00698126,
       0.00872654, 0.01047178, 0.012217  , 0.01396218, 0.01570732])

### Random dataset

In [56]:
X_degrees_random = np.random.uniform(0, 360, 5000)
X_radians_random = np.radians(X_degrees_random)
y_random = np.sin(X_radians_random)

In [58]:
print("Random Sample (Degrees):", X_degrees_random[:10])

Random Sample (Degrees): [146.08216413 346.2583107  353.21382752 259.09625779 344.68269291
 132.7256928  252.92081423 190.13196642 158.45019033 123.6712561 ]


In [60]:
X_radians_random.size

5000

In [66]:
X_radians_random[:10]

array([2.54961474, 6.04334758, 6.16474425, 4.52208278, 6.01584787,
       2.31650034, 4.41430096, 3.31842883, 2.76547752, 2.15847061])

In [74]:
y_random[:10]

array([ 0.55800346, -0.237545  , -0.11816433, -0.98194636, -0.2641644 ,
        0.73461042, -0.95589977, -0.17591597,  0.36730994,  0.83223237])

---

## Data Preprocessing: Splitting & Normalization

### Data Preprocessing: Splitting & Normalization

Before training our ANN model, we need to:
1. **Normalize the input values** to improve training efficiency.
2. **Split the dataset** into training and testing sets.

In [126]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split

In [131]:
scaler = MinMaxScaler(feature_range=(-1, 1))

In [133]:
X_radians_uniform = scaler.fit_transform(X_radians_uniform.reshape(-1, 1)).flatten()
X_radians_random = scaler.fit_transform(X_radians_random.reshape(-1, 1)).flatten()

#### Normalize the entire dataset first

In [137]:
X_radians_uniform = scaler.fit_transform(X_radians_uniform.reshape(-1, 1)).flatten()
X_radians_random = scaler.fit_transform(X_radians_random.reshape(-1, 1)).flatten()

#### Split into training and testing sets

In [140]:
X_train_uniform, X_test_uniform, y_train_uniform, y_test_uniform = train_test_split(
    X_radians_uniform, y_uniform, test_size=0.2, random_state=42
)

X_train_random, X_test_random, y_train_random, y_test_random = train_test_split(
    X_radians_random, y_random, test_size=0.2, random_state=42
)

---

## Define the ANN Model Architecture

In [167]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [169]:
ann = Sequential()

#### Input + First Hidden Layer

In [177]:
ann.add(Dense(units=16, activation='sigmoid', input_shape=(1,)))

In [173]:
# Additional Hidden Layers
ann.add(Dense(units=16, activation='sigmoid'))
ann.add(Dense(units=8, activation='sigmoid'))